//! Programmatic generators for the two oversized fixtures.
//!
//! Phase-4 skeleton checks in small, hand-edited versions of
//! `scn-03-table-large.md` and `scn-10-long-document.md`. SL-03 / SL-10
//! invoke these helpers (or commit the generated bytes) when they need the
//! full-sized variants.
//!
//! TRACE: SCN-03
//! TRACE: SCN-10

/// Generate a GFM table with `rows` data rows. SCN-03's full variant uses
/// `rows = 200`; the checked-in skeleton uses 12.
///
/// TRACE: SCN-03
pub fn generate_scn_03(rows: usize) -> String {
    let mut s = String::new();
    s.push_str("## Reference table\n\n");
    s.push_str("| Code   | Name              | Description                                         | Notes                  |\n");
    s.push_str("|--------|-------------------|-----------------------------------------------------|------------------------|\n");
    for i in 1..=rows {
        s.push_str(&format!(
            "| R-{i:04} | row-name-{i:04}    | Description for row {i:04} — short text            | row {i}                |\n"
        ));
    }
    s
}

/// Generate a long document with `sections` H2 sections, each containing
/// three short paragraphs. SCN-10's full variant uses `sections = 30`; the
/// checked-in skeleton uses 6.
///
/// TRACE: SCN-10
pub fn generate_scn_10(sections: usize) -> String {
    let mut s = String::new();
    for i in 1..=sections {
        s.push_str(&format!("## Section {i}\n\n"));
        s.push_str(&format!(
            "First paragraph of section {i}. Plain prose, no inline links.\n\n"
        ));
        s.push_str(&format!(
            "Second paragraph of section {i}. Two sentences. The batcher should split this section.\n\n"
        ));
        s.push_str(&format!(
            "Third paragraph of section {i}. One short sentence to round out the section.\n\n"
        ));
    }
    s
}
