// Playwright config for the SCN-13 headless sync suite.
//
// Chromium only, headless, single worker (the scroll-timing assertions
// want a quiet CPU and one shared static server). The webServer serves
// the CLI-emitted bundle — regenerated by scripts/test-browser.sh before
// each run — over loopback ONLY (127.0.0.1); nothing binds a public
// interface.
//
// Which server, and why there are two (ti b791d6): when
// TRANSYNC_SERVE_BIN names a built `transync` binary — which
// scripts/test-browser.sh always does — the suite runs against `transync
// serve`, the loopback server the CLI ships, so the SCN-13 evidence
// covers the real thing. The binary is built by that script before
// Playwright starts, so nothing compiles inside the startup timeout
// below, and readiness is still decided by polling `url` rather than
// assumed. Without the variable — a bare `pnpm exec playwright test`
// against an already-generated fixture — the small Node server in
// tests/support/ stands in, so the suite stays runnable with nothing but
// the fixture and node. The run log names whichever one started.
//
// TRACE: SCN-13
// TRACE: OI-0023

import { defineConfig, devices } from "@playwright/test";

// Loopback-only demo server. Port is fixed and uncommon to avoid
// colliding with the manual smoke server (scripts/smoke-live.sh uses
// 7470).
const HOST = "127.0.0.1";
const PORT = 4319;

// The bundle to serve. scripts/test-browser.sh regenerates it here right
// before invoking the suite; override with TRANSYNC_FIXTURE_DIR.
const FIXTURE_DIR =
  process.env.TRANSYNC_FIXTURE_DIR ||
  "/Volumes/Temp/claude/transync-browser-fixture/html";

// The built `transync` binary, when scripts/test-browser.sh resolved one.
const SERVE_BIN = process.env.TRANSYNC_SERVE_BIN;

export default defineConfig({
  testDir: "./tests",
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: 0,
  reporter: [["list"]],
  timeout: 30_000,
  expect: { timeout: 5_000 },
  use: {
    baseURL: `http://${HOST}:${PORT}`,
    viewport: { width: 1000, height: 700 },
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    // `transync serve` when the script handed us a binary; otherwise the
    // tiny Node stand-in (same runtime as the tests — no external
    // interpreter to locate/spawn). Both bind 127.0.0.1 only.
    command: SERVE_BIN
      ? `"${SERVE_BIN}" serve --rendered "${FIXTURE_DIR}" --bind ${HOST} --port ${PORT}`
      : `node ./tests/support/static-server.mjs "${FIXTURE_DIR}" ${PORT}`,
    url: `http://${HOST}:${PORT}/index.html`,
    timeout: 30_000,
    reuseExistingServer: !process.env.CI,
    stdout: "pipe",
    stderr: "pipe",
  },
});
