// Playwright config for the SCN-13 headless sync suite.
//
// Chromium only, headless, single worker (the scroll-timing assertions
// want a quiet CPU and one shared static server). The webServer serves
// the CLI-emitted bundle — regenerated by scripts/test-browser.sh before
// each run — over loopback ONLY (127.0.0.1); nothing binds a public
// interface.
//
// Which server, and why there are two (ti b791d6): when
// TRANSYNC_SERVE_BIN names a built `transync` binary — which
// scripts/test-browser.sh always does — the suite runs against `transync
// serve`, the loopback server the CLI ships, so the SCN-13 evidence
// covers the real thing. The binary is built by that script before
// Playwright starts, so nothing compiles inside the startup timeout
// below, and readiness is still decided by polling `url` rather than
// assumed. Without the variable — a bare `pnpm exec playwright test`
// against an already-generated fixture — the small Node server in
// tests/support/ stands in, so the suite stays runnable with nothing but
// the fixture and node. The run log names whichever one started.
//
// TRACE: SCN-13
// TRACE: OI-0023

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig, devices } from "@playwright/test";

const CONFIG_DIR = path.dirname(fileURLToPath(import.meta.url));

// Loopback-only demo server. Port is fixed and uncommon to avoid
// colliding with the manual smoke server (scripts/smoke-live.sh uses
// 7470).
const HOST = "127.0.0.1";
const PORT = 4319;

// The bundle to serve. Nothing in this repository tracks one — it is a
// CLI-emitted artifact — so the default is a repository-relative path a
// clean clone can actually name, not an absolute path that exists on one
// workstation. scripts/test-browser.sh regenerates the bundle under its own
// workdir and passes TRANSYNC_FIXTURE_DIR (absolute) explicitly; a bare
// `pnpm exec playwright test` gets this default and the check below.
const FIXTURE_DIR = path.resolve(
  process.env.TRANSYNC_FIXTURE_DIR || path.join(CONFIG_DIR, ".fixture", "html"),
);

// Fail here, with the command that fixes it, rather than 30 s later inside a
// webServer readiness timeout that says only that the URL never answered.
// Safe for the wrapper: `playwright install <browser>` does not load this
// file, and the wrapper regenerates the bundle before it runs the suite.
if (!fs.existsSync(FIXTURE_DIR)) {
  throw new Error(
    [
      `No rendered bundle at ${FIXTURE_DIR}.`,
      "This suite runs against a CLI-emitted bundle, which is generated, not tracked.",
      "Generate one and run the suite with:  ./scripts/test-browser.sh",
      "or point TRANSYNC_FIXTURE_DIR at an existing bundle directory.",
    ].join("\n"),
  );
}

// The built `transync` binary, when scripts/test-browser.sh resolved one.
const SERVE_BIN = process.env.TRANSYNC_SERVE_BIN;

export default defineConfig({
  testDir: "./tests",
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: 0,
  reporter: [["list"]],
  timeout: 30_000,
  expect: { timeout: 5_000 },
  use: {
    baseURL: `http://${HOST}:${PORT}`,
    viewport: { width: 1000, height: 700 },
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    // `transync serve` when the script handed us a binary; otherwise the
    // tiny Node stand-in (same runtime as the tests — no external
    // interpreter to locate/spawn). Both bind 127.0.0.1 only.
    command: SERVE_BIN
      ? `"${SERVE_BIN}" serve --rendered "${FIXTURE_DIR}" --bind ${HOST} --port ${PORT}`
      : `node ./tests/support/static-server.mjs "${FIXTURE_DIR}" ${PORT}`,
    url: `http://${HOST}:${PORT}/index.html`,
    timeout: 30_000,
    // Off by default (R0009-0017). Reuse keyed on "something answers this
    // port" is not proof of ownership: a leftover `transync serve` from an
    // aborted run, or any unrelated process, would silently stand in for the
    // server this config asked for and the suite would report a pass against
    // content it never built. With reuse off, an occupied port is a loud
    // startup failure instead. Set TRANSYNC_REUSE_SERVER=1 to opt back in
    // when you know what is listening.
    reuseExistingServer: process.env.TRANSYNC_REUSE_SERVER === "1",
    stdout: "pipe",
    stderr: "pipe",
  },
});
