// Playwright config for the SCN-13 headless sync suite.
//
// Chromium only, headless, single worker (the scroll-timing assertions
// want a quiet CPU and one shared static server). The webServer serves
// the CLI-emitted bundle — regenerated by scripts/test-browser.sh before
// each run — over loopback ONLY (127.0.0.1); nothing binds a public
// interface.
//
// Which server, and why there are two (ti b791d6): when
// TRANSYNC_SERVE_BIN names a built `transync` binary — which
// scripts/test-browser.sh always does — the suite runs against `transync
// serve`, the loopback server the CLI ships, so the SCN-13 evidence
// covers the real thing. The binary is built by that script before
// Playwright starts, so nothing compiles inside the startup timeout
// below, and readiness is still decided by polling `url` rather than
// assumed. Without the variable — a bare `pnpm exec playwright test`
// against an already-generated fixture — the small Node server in
// tests/support/ stands in, so the suite stays runnable with nothing but
// the fixture and node. The run log names whichever one started.
//
// TRACE: SCN-13
// TRACE: OI-0023

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig, devices } from "@playwright/test";

const CONFIG_DIR = path.dirname(fileURLToPath(import.meta.url));

// Loopback-only demo server. The default port is uncommon to avoid
// colliding with the manual smoke server (scripts/smoke-live.sh uses 7470)
// — but it was a bare literal, so it also collided with a SECOND run of
// this suite, and `reuseExistingServer` being off (below) turns that into a
// startup failure rather than a queue. TRANSYNC_BROWSER_PORT gives the
// second run somewhere to go (OI-0046, finding R0009-0018). With the
// variable unset, the port, both URLs and the trace directory are exactly
// what they were before the override existed.
//
// HOST is deliberately NOT overridable. tests/support/static-server.mjs
// hard-codes 127.0.0.1 and this config hands it only a directory and a
// port, so a host override would make `baseURL` and `webServer.url`
// disagree with what the stand-in actually binds — and loopback-only is a
// property this suite means to keep: nothing here binds a public interface.
const HOST = "127.0.0.1";
const DEFAULT_PORT = 4319;
// Unset or empty falls back; ANYTHING ELSE is parsed and must be a valid
// port. `Number(x) || DEFAULT_PORT` would be shorter and wrong: it turns a
// typo into a silent run on 4319, which is the collision this override
// exists to avoid, so a bad value has to be loud.
const PORT_OVERRIDE = process.env.TRANSYNC_BROWSER_PORT;
const PORT =
  PORT_OVERRIDE === undefined || PORT_OVERRIDE === "" ? DEFAULT_PORT : Number(PORT_OVERRIDE);
if (!Number.isInteger(PORT) || PORT < 1 || PORT > 65_535) {
  throw new Error(
    `TRANSYNC_BROWSER_PORT must be an integer port in 1-65535; got ${JSON.stringify(
      PORT_OVERRIDE,
    )}.`,
  );
}

// Playwright wipes its output directory when a run starts, so two runs
// sharing one directory destroy each other's traces — the same collision as
// the port, one step further along. Derived from the port, which is the one
// thing a second run has already had to change to get this far, and left at
// Playwright's own default path when the port is the default so an ordinary
// run writes exactly where it always did. `web/.gitignore` covers
// `test-results/`; a non-default port writes a sibling beside it.
const OUTPUT_DIR = PORT === DEFAULT_PORT ? "test-results" : `test-results-${PORT}`;

// The bundle to serve. Nothing in this repository tracks one — it is a
// CLI-emitted artifact — so the default is a repository-relative path a
// clean clone can actually name, not an absolute path that exists on one
// workstation. scripts/test-browser.sh regenerates the bundle under its own
// workdir and passes TRANSYNC_FIXTURE_DIR (absolute) explicitly; a bare
// `pnpm exec playwright test` gets this default and the check below.
const FIXTURE_DIR = path.resolve(
  process.env.TRANSYNC_FIXTURE_DIR || path.join(CONFIG_DIR, ".fixture", "html"),
);

// Fail here, with the command that fixes it, rather than 30 s later inside a
// webServer readiness timeout that says only that the URL never answered.
// Safe for the wrapper: `playwright install <browser>` does not load this
// file, and the wrapper regenerates the bundle before it runs the suite.
if (!fs.existsSync(FIXTURE_DIR)) {
  throw new Error(
    [
      `No rendered bundle at ${FIXTURE_DIR}.`,
      "This suite runs against a CLI-emitted bundle, which is generated, not tracked.",
      "Generate one and run the suite with:  ./scripts/test-browser.sh",
      "or point TRANSYNC_FIXTURE_DIR at an existing bundle directory.",
    ].join("\n"),
  );
}

// A bundle OLDER than the code that produces it is a pass against content the
// suite never built (ti `ed2e73`).
//
// scripts/test-browser.sh regenerates everything and then ends in a bare
// `pnpm exec playwright test`. Running that bare command directly — one
// `pnpm test` away — skips the regeneration and validates whatever the last
// full run left behind. The wave plans document that inner loop as a
// legitimate speed-up with the caveat that a pass must be re-confirmed by a
// full script run before a commit, and nothing ENFORCED the caveat: a stale
// bundle produces a confident green describing code no longer on disk.
//
// This is the same shape, and the same remedy, as `reuseExistingServer` below
// (R0009-0017): refuse by default, opt back in when you know what you have.
//
// `web/tests/**` is deliberately NOT an input. Editing a spec is exactly the
// case the inner loop exists for, and making that re-run the whole script
// would delete the affordance rather than guard it.
//
// TWO HONEST LIMITS, so nobody reads this as proof:
//
//   1. INPUTS ARE HAND-LISTED. This is a second statement of "what feeds the
//      bundle" — the first is test-browser.sh's own build and copy legs — and
//      it will drift when a leg is added. It is a floor, not a fence.
//   2. mtime IS A HEURISTIC, and it fails in one direction silently: checking
//      out an older branch leaves sources OLDER than the fixture, so the check
//      passes while the suite tests different code. Only "the bare path re-runs
//      the script" cannot lie, and that would remove the inner loop entirely.
//
// It does catch the case that found this ticket, which a bundle-content hash
// cannot: a Rust edit that was never built. The binary is unchanged, so its
// bytes match — but its source is newer than the bundle, and that is what this
// compares.
const BUNDLE_INPUTS = ["crates", "web/js", "web/vendor", "web/wasm"];
const BUNDLE_INPUT_FILES = ["web/index.html", "web/demo-wasm.html"];
const REPO_ROOT = path.resolve(CONFIG_DIR, "..");

/** Newest mtime under `dir`, skipping build output. `0` when absent. */
function newestMtime(dir) {
  let newest = 0;
  const walk = (abs) => {
    let entries;
    try {
      entries = fs.readdirSync(abs, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      // `target` is cargo's output and `node_modules` is pnpm's; both churn
      // constantly and neither feeds the bundle.
      if (entry.name === "target" || entry.name === "node_modules") continue;
      const child = path.join(abs, entry.name);
      if (entry.isDirectory()) {
        walk(child);
      } else {
        try {
          newest = Math.max(newest, fs.statSync(child).mtimeMs);
        } catch {
          /* raced away between readdir and stat; not our business */
        }
      }
    }
  };
  walk(dir);
  return newest;
}

const fixtureBuiltAt = newestMtime(FIXTURE_DIR);
let newestInput = 0;
let newestInputPath = null;
for (const rel of [...BUNDLE_INPUTS, ...BUNDLE_INPUT_FILES]) {
  const abs = path.join(REPO_ROOT, rel);
  const at =
    fs.existsSync(abs) && fs.statSync(abs).isDirectory()
      ? newestMtime(abs)
      : fs.existsSync(abs)
        ? fs.statSync(abs).mtimeMs
        : 0;
  if (at > newestInput) {
    newestInput = at;
    newestInputPath = rel;
  }
}

if (fixtureBuiltAt > 0 && newestInput > fixtureBuiltAt) {
  const age = Math.round((newestInput - fixtureBuiltAt) / 60_000);
  const message = [
    `The bundle at ${FIXTURE_DIR} is older than the code that produces it.`,
    `Newest input: ${newestInputPath} (${age} minute(s) newer than the bundle).`,
    "A run against it would green a bundle that predates your edits.",
    "Regenerate and run the suite with:  ./scripts/test-browser.sh",
    "Set TRANSYNC_ALLOW_STALE_FIXTURE=1 to downgrade this to a warning when you",
    "know the bundle is current for what you are testing (e.g. a spec-only edit).",
  ].join("\n");
  if (process.env.TRANSYNC_ALLOW_STALE_FIXTURE === "1") {
    process.stderr.write(`playwright.config.js: WARNING — stale bundle\n${message}\n`);
  } else {
    throw new Error(message);
  }
}

// The built `transync` binary, when scripts/test-browser.sh resolved one.
const SERVE_BIN = process.env.TRANSYNC_SERVE_BIN;

export default defineConfig({
  testDir: "./tests",
  outputDir: OUTPUT_DIR,
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: 0,
  reporter: [["list"]],
  timeout: 30_000,
  expect: { timeout: 5_000 },
  use: {
    baseURL: `http://${HOST}:${PORT}`,
    viewport: { width: 1000, height: 700 },
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    // `transync serve` when the script handed us a binary; otherwise the
    // tiny Node stand-in (same runtime as the tests — no external
    // interpreter to locate/spawn). Both bind 127.0.0.1 only.
    command: SERVE_BIN
      ? `"${SERVE_BIN}" serve --rendered "${FIXTURE_DIR}" --bind ${HOST} --port ${PORT}`
      : `node ./tests/support/static-server.mjs "${FIXTURE_DIR}" ${PORT}`,
    url: `http://${HOST}:${PORT}/index.html`,
    timeout: 30_000,
    // Off by default (R0009-0017). Reuse keyed on "something answers this
    // port" is not proof of ownership: a leftover `transync serve` from an
    // aborted run, or any unrelated process, would silently stand in for the
    // server this config asked for and the suite would report a pass against
    // content it never built. With reuse off, an occupied port is a loud
    // startup failure instead. Set TRANSYNC_REUSE_SERVER=1 to opt back in
    // when you know what is listening.
    reuseExistingServer: process.env.TRANSYNC_REUSE_SERVER === "1",
    stdout: "pipe",
    stderr: "pipe",
  },
});
